AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - '**/vendor/bundle/**/*' # Resolves Rubocop issue with GitHub CI Action